version: '3.7'

services:
  # infrastructure
  postgres:
    image: 'postgres:15.4'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - pg_data:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - '9001:9001'
    depends_on:
      - postgres

volumes:
  pg_data:
